base_url: /hub-guide-en
title: FOSSLight Hub Guide
lang: en
description: FOSSLight Hub English Guide

remote_theme: fosslight/guide_theme

top_link: "https://fosslight.github.io/hub-guide"
top_link_word: "Korean"

addons_title: "FOSSLight Homepage"
addons_url: "https://fosslight.org/en"

google:
  gtag: G-F57FX89C25

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
